/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-06-21 08:02:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._09Board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model1.*;
import java.util.*;

public final class List_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("model1");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

	BoardDao boardDao = new BoardDao(application); //DB 열기
	Map<String, Object> map = new HashMap<>();

	String searchField = request.getParameter("searchField");
	String searchWord = request.getParameter("searchWord");

	if (searchWord != null) {
		map.put("searchField", searchField);
		map.put("searchWord", searchWord);
	}

	int totalCount = boardDao.selectCount(map); //해당 검색된 게시물의 총개수
	List<BoardDto> boardLists = boardDao.selectList(map); //해당 검색된 게시물 전부

	boardDao.JDBConnecterClose(); //DB 닫기
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../07Common/Link.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- 공통 링크 -->\r\n");
      out.write("\r\n");
      out.write("	<h2>목록 보기(List)</h2>\r\n");
      out.write("	<!-- 검색폼 -->\r\n");
      out.write("	<form method=\"get\">\r\n");
      out.write("		<table border=\"1\" width=\"90%\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\"><select name=\"searchField\">\r\n");
      out.write("						<option value=\"title\">제목</option>\r\n");
      out.write("						<option value=\"content\">내용</option>\r\n");
      out.write("				</select> <input type=\"text\" name=\"searchWord\" /> <input type=\"submit\" value=\"검색하기\" /></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("	<!-- 게시물 목록 테이블(표) -->\r\n");
      out.write("	<table border=\"1\" width=\"90%\">\r\n");
      out.write("		<!-- 각 칼럼의 이름 -->\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"10%\">번호</th>\r\n");
      out.write("			<th width=\"50%\">제목</th>\r\n");
      out.write("			<th width=\"15%\">작성자</th>\r\n");
      out.write("			<th width=\"10%\">조회수</th>\r\n");
      out.write("			<th width=\"15%\">작성일</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<!-- 목록의 내용 -->\r\n");
      out.write("		");

		if (boardLists.isEmpty()) {
			// 게시물이 하나도 없을 때
		
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"5\" align=\"center\">등록된 게시물이 없습니다^^*</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

		} else {
		// 게시물이 있을 때 
		int virtualNum = 0; // 화면상에서의 게시물 번호
		for (BoardDto dto : boardLists) {
			virtualNum = totalCount--; // 전체 게시물 수에서 시작해 1씩 감소
		
      out.write("\r\n");
      out.write("		<tr align=\"center\">\r\n");
      out.write("			<td>");
      out.print(virtualNum);
      out.write("</td>\r\n");
      out.write("			<!--게시물 번호-->\r\n");
      out.write("			<td align=\"left\">\r\n");
      out.write("				<!--제목(+ 하이퍼링크)--> <a href=\"View.jsp?num=");
      out.print(dto.getNum());
      out.write('"');
      out.write('>');
      out.print(dto.getTitle());
      out.write("</a>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align=\"center\">");
      out.print(dto.getId());
      out.write("</td>\r\n");
      out.write("			<!--작성자 아이디-->\r\n");
      out.write("			<td align=\"center\">");
      out.print(dto.getVisitcount());
      out.write("</td>\r\n");
      out.write("			<!--조회수-->\r\n");
      out.write("			<td align=\"center\">");
      out.print(dto.getPostdate());
      out.write("</td>\r\n");
      out.write("			<!--작성일-->\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

		}
		}
		
      out.write("\r\n");
      out.write("	</table>\r\n");
      out.write("	<!--목록 하단의 [글쓰기] 버튼-->\r\n");
      out.write("	<table border=\"1\" width=\"90%\">\r\n");
      out.write("		<tr align=\"right\">\r\n");
      out.write("			<td><button type=\"button\" onclick=\"location.href='Write.jsp';\">글쓰기</button></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
